//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersToEvent
    {
        public int Id { get; set; }
        public int IdEvent { get; set; }
        public int IdUser { get; set; }
    
        public virtual EventsPost EventsPost { get; set; }
        public virtual Users Users { get; set; }
    }
}
